nelmio_cors:
    defaults:
        allow_origin: ['%env(CORS_ALLOW_ORIGINS)%']
        allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
        allow_headers: ['Content-Type','Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGINS)%']
            allow_credentials: true
